name: QuartzNet15x5
model:
  sample_rate: 16000
  repeat: 5
  dropout: 0.0
  separable: true
  labels: &id001
  - ' '
  - a
  - b
  - c
  - d
  - e
  - f
  - g
  - h
  - i
  - j
  - k
  - l
  - m
  - n
  - o
  - p
  - q
  - r
  - s
  - t
  - u
  - v
  - w
  - x
  - y
  - z
  - ''''
  - á
  - é
  - í
  - ó
  - ú
  - ñ
  - ü
  train_ds:
    manifest_filepath: ???
    sample_rate: 16000
    labels: *id001
    batch_size: 32
    trim_silence: true
    max_duration: 16.7
    shuffle: true
    num_workers: 8
    pin_memory: true
    is_tarred: false
    tarred_audio_filepaths: null
    shuffle_n: 2048
    bucketing_strategy: synced_randomized
    bucketing_batch_size: null
  validation_ds:
    manifest_filepath: ???
    sample_rate: 16000
    labels: *id001
    batch_size: 32
    shuffle: false
    num_workers: 8
    pin_memory: true
  test_ds:
    manifest_filepath: null
    sample_rate: 16000
    labels: *id001
    batch_size: 32
    shuffle: false
    num_workers: 8
    pin_memory: true
  preprocessor:
    _target_: nemo.collections.asr.modules.AudioToMelSpectrogramPreprocessor
    normalize: per_feature
    window_size: 0.02
    sample_rate: 16000
    window_stride: 0.01
    window: hann
    features: 64
    n_fft: 512
    frame_splicing: 1
    dither: 1.0e-05
  spec_augment:
    _target_: nemo.collections.asr.modules.SpectrogramAugmentation
    rect_freq: 50
    rect_masks: 5
    rect_time: 120
  encoder:
    _target_: nemo.collections.asr.modules.ConvASREncoder
    feat_in: 64
    activation: relu
    conv_mask: true
    jasper:
    - dilation:
      - 1
      dropout: 0.0
      filters: 256
      kernel:
      - 33
      repeat: 1
      residual: false
      separable: true
      stride:
      - 2
    - dilation:
      - 1
      dropout: 0.0
      filters: 256
      kernel:
      - 33
      repeat: 5
      residual: true
      separable: true
      stride:
      - 1
    - dilation:
      - 1
      dropout: 0.0
      filters: 256
      kernel:
      - 33
      repeat: 5
      residual: true
      separable: true
      stride:
      - 1
    - dilation:
      - 1
      dropout: 0.0
      filters: 256
      kernel:
      - 33
      repeat: 5
      residual: true
      separable: true
      stride:
      - 1
    - dilation:
      - 1
      dropout: 0.0
      filters: 256
      kernel:
      - 39
      repeat: 5
      residual: true
      separable: true
      stride:
      - 1
    - dilation:
      - 1
      dropout: 0.0
      filters: 256
      kernel:
      - 39
      repeat: 5
      residual: true
      separable: true
      stride:
      - 1
    - dilation:
      - 1
      dropout: 0.0
      filters: 256
      kernel:
      - 39
      repeat: 5
      residual: true
      separable: true
      stride:
      - 1
    - dilation:
      - 1
      dropout: 0.0
      filters: 512
      kernel:
      - 51
      repeat: 5
      residual: true
      separable: true
      stride:
      - 1
    - dilation:
      - 1
      dropout: 0.0
      filters: 512
      kernel:
      - 51
      repeat: 5
      residual: true
      separable: true
      stride:
      - 1
    - dilation:
      - 1
      dropout: 0.0
      filters: 512
      kernel:
      - 51
      repeat: 5
      residual: true
      separable: true
      stride:
      - 1
    - dilation:
      - 1
      dropout: 0.0
      filters: 512
      kernel:
      - 63
      repeat: 5
      residual: true
      separable: true
      stride:
      - 1
    - dilation:
      - 1
      dropout: 0.0
      filters: 512
      kernel:
      - 63
      repeat: 5
      residual: true
      separable: true
      stride:
      - 1
    - dilation:
      - 1
      dropout: 0.0
      filters: 512
      kernel:
      - 63
      repeat: 5
      residual: true
      separable: true
      stride:
      - 1
    - dilation:
      - 1
      dropout: 0.0
      filters: 512
      kernel:
      - 75
      repeat: 5
      residual: true
      separable: true
      stride:
      - 1
    - dilation:
      - 1
      dropout: 0.0
      filters: 512
      kernel:
      - 75
      repeat: 5
      residual: true
      separable: true
      stride:
      - 1
    - dilation:
      - 1
      dropout: 0.0
      filters: 512
      kernel:
      - 75
      repeat: 5
      residual: true
      separable: true
      stride:
      - 1
    - dilation:
      - 2
      dropout: 0.0
      filters: 512
      kernel:
      - 87
      repeat: 1
      residual: false
      separable: true
      stride:
      - 1
    - dilation:
      - 1
      dropout: 0.0
      filters: 1024
      kernel:
      - 1
      repeat: 1
      residual: false
      stride:
      - 1
  decoder:
    _target_: nemo.collections.asr.modules.ConvASRDecoder
    feat_in: 1024
    num_classes: 35
    vocabulary: *id001
  optim:
    name: novograd
    lr: 0.01
    betas:
    - 0.8
    - 0.5
    weight_decay: 0.001
    sched:
      name: CosineAnnealing
      warmup_steps: null
      warmup_ratio: null
      min_lr: 0.0
      last_epoch: -1
trainer:
  devices: 1
  max_epochs: 5
  max_steps: -1
  num_nodes: 1
  accelerator: gpu
  strategy: ddp
  accumulate_grad_batches: 1
  enable_checkpointing: false
  logger: false
  log_every_n_steps: 1
  val_check_interval: 1.0
  benchmark: false
exp_manager:
  exp_dir: null
  name: QuartzNet15x5
  create_tensorboard_logger: true #true ##true == original value
  create_checkpoint_callback: false #true ##true == original value
  checkpoint_callback_params:
    monitor: val_wer
    mode: min
  create_wandb_logger: false
  wandb_logger_kwargs:
    name: null
    project: null
